name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22ds3000157@ds.study.iitm.ac.in
        run: echo "Hello, world!"
